/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val arr_1: Array<Int> = arrayOf(1, 4, 4, 3, -4, -5, 6, 0, -1)
    
    println("Исходный массив: ${arr_1.joinToString(", ")}")

    println("Минимальный четный элемент массива ${arr_1.filter {it % 2 == 0 }.minOrNull()}")
    println("Сумма элементов массива ${arr_1.sum()}")
    println("Отрицательные элементы массива ${arr_1.filter {it < 0 }.joinToString(", ")}")
}
